### ISSUE TITLE
Plugin upgrade

### ISSUE THREAD

**Issue by ndawod** [jaehyunup/kotlin-auto-fill#10]
Seems like the plugin needs a new build...

`Plugin 'Kotlin Auto fill' (version '1.0.5') is not compatible with the current version of the IDE, because it requires build 241.* or older but the current build is IU-242.20224.387`

**Comment by jaehyunup** [comment]
We apologize for keeping you guys waiting, we have updated support for version 2024.2 and are currently working on the intellij plugin verify pipeline. You should see it in the IDE in the next few days. 

Thank you for using this plugin and for your interest.
