### ISSUE TITLE
Need to support 2024.2

### ISSUE THREAD

**Issue by ltttttttttttt** [jaehyunup/kotlin-auto-fill#11]

**Comment by abn-dev-01** [comment]
<img width="388" alt="image" src="https://github.com/user-attachments/assets/f77f6f19-70a6-4235-a1ec-746e01920064">

**Comment by michaldrabik** [comment]
> Not compatible with the version of your running IDE (Android Studio Ladybug | 2024.2.1 Patch 2)

Any plans on an update?

**Comment by jaehyunup** [comment]
We apologize for keeping you guys waiting, we have updated support for version 2024.2 and are currently working on the intellij plugin verify pipeline. You should see it in the IDE in the next few days. 

Thank you for using this plugin and for your interest.
