### ISSUE TITLE
Compatibility with IntelliJ IDEA 2023.2.2

### ISSUE THREAD

**Issue by alexopenkowski** [jaehyunup/kotlin-auto-fill#3]
I really miss your plugin since I recently updated to the latest IntelliJ IDEA 2023.2.2. Could you release a compatible version, please? 😇

**Comment by jaehyunup** [comment]
I haven't paid attention to version upgrades for a while. Thank you for your interest.
I will update to the version supported by the latest version of the IDE.

I'm sorry to keep you waiting
