### ISSUE TITLE
Not compatible with K2 compiler

### ISSUE THREAD

**Issue by lemcoder** [jaehyunup/kotlin-auto-fill#9]
![image](https://github.com/jaehyunup/kotlin-auto-fill/assets/69146893/c22e853b-9a90-40fc-a7dc-4cabd753ffa0)

**Comment by lydlovezjr** [comment]
plugin is incompatible with K2 mode

**Comment by jaehyunup** [comment]
Sorry, we're still looking into adding support for the K2 compiler to the plugin. We'll announce this news as soon as possible.
